// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TheBookDen.DataAccess.Data;

#nullable disable

namespace TheBookDen.DataAccess.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20240809032237_SeedCategoryTable")]
partial class SeedCategoryTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TheBookDenWeb.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Categories");

                b.HasData(
                    new
                    {
                        Id = 1,
                        DisplayOrder = 1,
                        Name = "Action"
                    },
                    new
                    {
                        Id = 2,
                        DisplayOrder = 1,
                        Name = "SciFi"
                    },
                    new
                    {
                        Id = 3,
                        DisplayOrder = 1,
                        Name = "History"
                    });
            });
#pragma warning restore 612, 618
    }
}
